name: RyoServerAssist
version: 1.0.0
main: com.ryoserver.RyoServerAssist
api-version: 1.17
author: rito528

default-permission-message: 権限がありません！
commands:
  home:
    description: Use home command.
    permission: ryoserverassist.home
  gacha:
    description: Gacha operation command.
    permission: ryoserverassist.gacha
  distribution:
    description: Distribution operation command.
    permission: ryoserverassist.distribution

permissions:
  ryoserverassist.*:
    default: false
    children:
      - ryoserverassist.home
      - ryoserverassist.gacha
      - ryoserverassist.distribution
  ryoserverassist.home:
    default: true
  ryoserverassist.gacha:
    default: op
  ryoserverassist.distribution:
    default: op