name: RyoServerAssist
version: 1.0.0
main: com.ryoserver.RyoServerAssist
api-version: 1.17
author: rito528
commands:
  home:
    usage: /home

permissions:
  home.*:
    default: true
    children:
      home.set: true
      home.tp: true
  home.set:
    default: true
  home.tp:
    default: true