#名前を変えるか、ファイルを移動すれば初期状態のconfigが生成されます。
#迷ったら初期状態のconfigを確認すること！

#SQL関係の設定
host: ''
user: ''
pw: ''
db: 'RyoServerAssist'

#ホーム機能を利用したときにログを出すかどうか
log: true

#日本語変換サーバーのIPアドレスを入力してください。
JapaneseChatServerIP: ''
#日本語変換サーバーのポートを入力してください。
JapaneseChatServerPort: 8080

#ガチャの排出確率設定(設定されなかった残りの割合ではずれが排出されます。%で指定してください。)
#はずれの割合が0%以下にならないように指定してください。
#あたり
per: 20.0
#大当たり
bigPer: 1.0
#特等
Special: 0.1