name: RyoServerAssist
version: 1.3.0
main: com.ryoserver.RyoServerAssist
api-version: 1.17
description: RyoServerAssist
depends: [WorldGuard,Votifier]
softdepend: [WorldGuard,Multiverse-Core,Multiverse-Portals,dynmap,Votifier]
author: rito528


commands:
  home:
    description: Use home command.
    permission: ryoserverassist.home
  gacha:
    description: Gacha operation command.
    permission: ryoserverassist.gacha
  distribution:
    description: Distribution operation command.
    permission: ryoserverassist.distribution
  menu:
    description: Menu open command.
    permission: ryoserverassist.menu
  level:
    description: level operation command.
    permission: ryoserverassist.level
  tpa:
    description: tpa command.
    permission: ryoserverassist.tpa
  skill:
    description: skill operation command.
    permission: ryoserverassist.skill
  stick:
    description: add stick command.
    permission: ryoserverassist.stick
  sr:
    description: region operation command.
    permission: ryoserverassist.sr
  hat:
    description: hat command.
    permission: ryoserverassist.hat
  spawn:
    description: spawn command.
    permission: ryoserverassist.spawn
  player:
    description: player operation command.
    permission: ryoserverassist.player
  title:
    description: title operation command.
    permission: ryoserverassist.title
  regeneration:
    description: world regeneration command.
    permission: ryoserverassist.title
  getoriginalitem:
    description: original item give command.
    permission: ryoserverassist.getoriginalitem
  playerStatus:
    description: player status check command.
    permission: ryoserverassist.playerstatus
  openInventory:
    description: player inventory check command.
    permission: ryoserverassist.openinventory
  openEnderChest:
    description: player enderChest check command.
    permission: ryoserverassist.openenderchest
  hide:
    description: hide command.
    permission: ryoserverassist.hide
  show:
    description: show command.
    permission: ryoserverassist.show
  freeze:
    description: freeze command.
    permission: ryoserverassist.freeze
  unfreeze:
    description: unfreeze command.
    permission: ryoserverassist.unfreeze
  security:
    description: security command.
    permission: ryoserverassist.security

permissions:
  ryoserverassist.*:
    default: false
    children:
      - ryoserverassist.home
      - ryoserverassist.gacha
      - ryoserverassist.distribution
      - ryoserverassist.menu
      - ryoserverassist.level
      - ryoserverassist.tpa
      - ryoserverassist.skill
      - ryoserverassist.stick
      - ryoserverassist.sr
      - ryoserverassist.hat
      - ryoserverassist.spawn
      - ryoserverassist.player
      - ryoserverassist.title
      - ryoserverassist.regeneration
      - ryoserverassist.getoriginalitem
      - ryoserverassist.playerstatus
      - ryoserverassist.openinventory
      - ryoserverassist.openenderchest
      - ryoserverassist.hide
      - ryoserverassist.show
      - ryoserverassist.freeze
      - ryoserverassist.unfreeze
      - ryoserverassist.security
      - ryoserverassist.commandExecuter
  ryoserverassist.home:
    default: true
  ryoserverassist.gacha:
    default: op
  ryoserverassist.distribution:
    default: op
  ryoserverassist.menu:
    default: true
  ryoserverassist.level:
    default: op
  ryoserverassist.tpa:
    default: true
  ryoserverassist.skill:
    default: op
  ryoserverassist.stick:
    default: true
  ryoserverassist.sr:
    default: op
  ryoserverassist.hat:
    default: true
  ryoserverassist.spawn:
    default: true
  ryoserverassist.player:
    default: op
  ryoserverassist.title:
    default: op
  ryoserverassist.regeneration:
    default: op
  ryoserverassist.getoriginalitem:
    default: op
  ryoserverassist.playerstatus:
    default: op
  ryoserverassist.openinventory:
    default: op
  ryoserverassist.openenderchest:
    default: op
  ryoserverassist.hide:
    default: op
  ryoserverassist.show:
    default: op
  ryoserverassist.freeze:
    default: op
  ryoserverassist.unfreeze:
    default: op
  ryoserverassist.security:
    default: op
  ryoserverassist.commandExecuter:
    default: op