name: RyoServerAssist
version: 1.5.0
main: com.ryoserver.RyoServerAssist
api-version: 1.17
description: RyoServerAssist
depends: [ WorldGuard,Votifier ]
softdepend: [ WorldGuard,Multiverse-Core,Multiverse-Portals,dynmap,Votifier ]
author: rito528


commands:
  home:
    description: Use home command.
    permission: ryoserverassist.home
  gacha:
    description: Gacha operation command.
    permission: ryoserverassist.gacha
  distribution:
    description: Distribution operation command.
    permission: ryoserverassist.distribution
  menu:
    description: Menu open command.
    permission: ryoserverassist.menu
  level:
    description: level operation command.
    permission: ryoserverassist.level
  tpa:
    description: tpa command.
    permission: ryoserverassist.tpa
  stick:
    description: add stick command.
    permission: ryoserverassist.stick
  sr:
    description: region operation command.
    permission: ryoserverassist.sr
  hat:
    description: hat command.
    permission: ryoserverassist.hat
  spawn:
    description: spawn command.
    permission: ryoserverassist.spawn
  player:
    description: player operation command.
    permission: ryoserverassist.player
  title:
    description: title operation command.
    permission: ryoserverassist.title
  regeneration:
    description: world regeneration command.
    permission: ryoserverassist.title
  getoriginalitem:
    description: original item give command.
    permission: ryoserverassist.getoriginalitem
  security:
    description: security command.
    permission: ryoserverassist.security
  profile:
    description: profile command.
    permission: ryoserverassist.profile
  skillPoint:
    description: set skill point command.
    permission: ryoserverassist.skillpoint

permissions:
  ryoserverassist.*:
    default: false
    children:
      - ryoserverassist.home
      - ryoserverassist.gacha
      - ryoserverassist.distribution
      - ryoserverassist.menu
      - ryoserverassist.level
      - ryoserverassist.tpa
      - ryoserverassist.stick
      - ryoserverassist.sr
      - ryoserverassist.hat
      - ryoserverassist.spawn
      - ryoserverassist.player
      - ryoserverassist.title
      - ryoserverassist.regeneration
      - ryoserverassist.getoriginalitem
      - ryoserverassist.security
      - ryoserverassist.commandExecuter
      - ryoserverassist.profile
      - ryoserverassist.skillpoint
  ryoserverassist.home:
    default: true
  ryoserverassist.gacha:
    default: op
  ryoserverassist.distribution:
    default: op
  ryoserverassist.menu:
    default: true
  ryoserverassist.level:
    default: op
  ryoserverassist.tpa:
    default: true
  ryoserverassist.stick:
    default: true
  ryoserverassist.sr:
    default: op
  ryoserverassist.hat:
    default: true
  ryoserverassist.spawn:
    default: true
  ryoserverassist.player:
    default: op
  ryoserverassist.title:
    default: op
  ryoserverassist.regeneration:
    default: op
  ryoserverassist.getoriginalitem:
    default: op
  ryoserverassist.security:
    default: op
  ryoserverassist.commandExecuter:
    default: op
  ryoserverassist.profile:
    default: true
  ryoserverassist.skillpoint:
    default: op