name: RyoServerAssist
version: @version@
main: com.ryoserver.RyoServerAssist
api-version: 1.17
author: rito528

default-permission-message: 権限がありません！
commands:
  home:
    description: Use home command.
    permission: ryoserverassist.home

permissions:
  ryoserverassist.*:
    default: false
    children:
      - ryoserverassist.home
  ryoserverassist.home:
    default: true