name: Votifier
main: com.vexsoftware.votifier.NuVotifierBukkit
version: 2.6.0
description: A plugin that gets notified when votes are made for the server on toplists.
authors: [Ichbinjoe, blakeman8192, Kramer, tuxed]
api-version: 1.13

commands:
  nvreload:
    description: Reloads the NuVotifier configuration
    permission: nuvotifier.console
    permission-message: "You do not have permission to run this command."
    usage: "/nvreload"