ALTER TABLE StackData CHANGE `id` `id` INT(11) NOT NULL;
ALTER TABLE StackData DROP PRIMARY KEY, ADD PRIMARY KEY (UUID(128));
ALTER TABLE StackData DROP COLUMN category;
ALTER TABLE StackData DROP COLUMN id;
ALTER TABLE StackList CHANGE `id` `id` INT(11) NOT NULL;
ALTER TABLE StackList DROP PRIMARY KEY, ADD PRIMARY KEY(category(20),page);
ALTER TABLE StackList DROP COLUMN id;