ALTER TABLE StackData CHANGE `id` `id` INT(11) NOT NULL;
ALTER TABLE StackData DROP PRIMARY KEY, ADD PRIMARY KEY (UUID(128));
ALTER TABLE StackData DROP COLUMN category;
ALTER TABLE StackData DROP COLUMN id;